CREATE TABLE IF NOT EXISTS food_items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255),
  quantity INT NOT NULL DEFAULT 1,
  expiration_date VARCHAR(255)
);